### ISSUE TITLE
PDFs with forms

### ISSUE THREAD

**Issue by lesolorzanov** [svenssonaxel/pdf-sign#11] opened 2024-06-29 13:53 UTC
I tried this with a PDF with a form and the form stops working, it is rasterized, I was wondering if this was taken into account. Is pretty nice otherwise.

**Comment by svenssonaxel** [comment] 2024-06-30 16:59
First, let's clarify:

* "Rasterize" means to convert to pixel graphics. If you zoom in far enough on something rasterized, you'll see it is pixelated, a less sharp image.
* "Flatten" means to merge the contents of a PDF form into the document itself, making it non-editable.

`pdf-sign` should not rasterize anything, if it does then it's a bug. It does however flatten before signing, by design. This is since you usually would not want to change anything in the form after signing, even accidentally. You can turn off flattening with the `--no-flatten` command-line option.

I noticed that the help text does not inform the user that `--flatten` is on by default. This should be fixed.

@lesolorzanov Could you clarify if the behavior you see is rasterization or flattening? Did the above explanation help you?

**Closed as completed** 2024-07-16 21:11 UTC

**Comment by svenssonaxel** [comment] 2024-07-16 21:13
@lesolorzanov I clarified the help text in the hope of solving this issue. Feel free to reopen if it is not solved.
